### ISSUE TITLE
Add subnet ID label to metrics

### ISSUE THREAD

**Issue by holmesb** [mweinelt/kea-exporter#15]
Would be useful to include.  I think most users will be specifying their own rather than allow Kea to auto-assign, as otherwise config changes can cause problems.  If others are like us, the chosen subnet IDs are more meaningful than CIDRs.

**Comment by mweinelt** [comment]
Hi, thanks for your input.

We're already using the subnet ID to match the correct subnet and since it has low cardinality I can certainly expose it in addition to the subnet. It is probably also more stable, since it is unaffected by renumbering.

Can you give the linked patch a try and report back?

**Comment by holmesb** [comment]
Hi @mweinelt, subnet IDs successfully showing in prometheus.  Patch looks good to me.  Thanks for such a quick turnaround on this.
